#Skonic Configuration

settings:
  # Enable this if you want more detailed error reports.
  debug: false
  # Enable this to automatically check for Skonic updates
  # Disable this if you do not want to check for updates, or causes issues while checking.
  update-checker:
      # Whether or not to check for updates
      enabled: true
  # Citizens configuration
  citizens:
      # Citizens pathfinding configuration
      pathfinding:
          # The range within which NPCs can move. Calculated by how many blocks it will use to pathfind to the location.
          # May not be the actual distance between the npc and the location.
          maximum-range: 75